version: '3.5'

services:
  postgres:
    container_name: postgres_pres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "6789:5432"
